services:
  cloudflared:
    image: cloudflare/cloudflared
    container_name: cloudflared

  db:
    image: postgres
    container_name: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=testme123
  web:
    build: .
    container_name: django
    environment:
      - DEBUG=on
      - SECRET_KEY="wb1j9+vxe2b#1dfu+2zgiaoa1v@q@wub15i75r=!*mol39k-qo"
      - DATABASE_URL=postgres://postgres:testme123@db:5432/postgres
      - AWS_S3_ACCESS_KEY_ID=your_minio_access_key
      - AWS_S3_SECRET_ACCESS_KEY=your_minio_secret_key
      - AWS_S3_BUCKET_NAME=main
      - AWS_S3_ENDPOINT_URL=http://s3:9000
    develop:
      watch:
        - action: sync
          path: .
          target: /app
    ports:
      - "8000:8994"
    depends_on:
      - db
#      - createbucket