services:
  db:
    image: postgres
    container_name: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=testme123
  web:
    build: .
    container_name: django
    volumes:
      - ./app:/code
    env_file: ".env"
    environment:
      - DATABASE_URL=postgres://postgres:testme123@db:5432/postgres
      - DJANGO_SUPERUSER_PASSWORD=testme123
    ports:
      - "8994:8994"
    command: ["python", "manage.py", "migrate"]
    depends_on:
      - db