services:
  cloudflared:
    image: cloudflare/cloudflared
    container_name: cloudflared
    env_file: "prod.env"
    command: tunnel --no-autoupdate run
    restart: unless-stopped
    depends_on:
      - webapp
  db:
    image: postgres
    container_name: postgres
    env_file: "prod.env"
    volumes:
      - ./data/prd/db:/var/lib/postgresql/data
  webapp:
    image: dvermaas/django:latest
    container_name: django
    env_file: "prod.env"
    develop:
      watch:
        - action: sync
          path: .
          target: /app
    depends_on:
      - db
      - minio
  minio:
    image: 'bitnami/minio:latest'
    container_name: minio
    env_file: "prod.env"
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./data/minio:/bitnami/minio/data