services:
  cloudflared:
    image: cloudflare/cloudflared
    container_name: cloudflared
    command: tunnel --no-autoupdate run
    env_file: "cloudflared.env"
    restart: unless-stopped
    depends_on:
      - webapp
  db:
    image: postgres
    container_name: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=testme123
  webapp:
    build: .
    container_name: django
    volumes:
      - ./data/app:/app
    env_file: "webapp.env"
    ports:
      - "8000:8994"
    develop:
      watch:
        - action: sync
          path: .
          target: /app
    depends_on:
      - db