services:
  db:
    image: postgres
    container_name: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=testme123
  s3:
    image: bitnami/minio
    container_name: minio
    volumes:
      - ./data/minio_data:/data
    environment:
      - MINIO_ACCESS_KEY=your_minio_access_key
      - MINIO_SECRET_KEY=your_minio_secret_key
    ports:
      - "9000:9000"
      - "9001:9001"
  createbucket:
    image: minio/mc
    depends_on:
      - s3
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add --api s3v4 s3 http://minio:9000 minio miniosecret;
      /usr/bin/mc mb s3/static/;
      /usr/bin/mc anonymous set download s3/static;
      "
  web:
    build: .
    container_name: django
    volumes:
      - .:/app
    env_file: ".env"
    environment:
      - DATABASE_URL=postgres://postgres:testme123@db:5432/postgres
      - DJANGO_SUPERUSER_PASSWORD=testme123
      - AWS_S3_ENDPOINT_URL=http://s3:9000
    ports:
      - "8994:8994"
    command: ["python", "manage.py", "migrate"]
    depends_on:
      - db
      - createbucket